export default [
	"First Meeting with Mircea",
	"If all we figure out in the first meeting is: we know what we're making, we're good!",
	"Come up with a meeting agenda",
	"PLAN A: An extension that redirects you to our microlearning website, then back to the extension",
	"Come up with list of ideas / Brainstorm app ideas",
	"Read both papers provided by Mircea",
	"Introduction to Svelte Scrimba (John)",
	"Google Extensions vid (John)",
	"Svelte Videos (John)",
	"Begin to familiarize ourselves with Svelte (Take notes while learning)",
	"Compile the notes somewhere!",
	"(Microlearning)",
	"Take a look at Codecademy’s Quizzes?",
	"Take a look at SoloLearn?",
	"Take a look at Duolingo?",
	"Look for other microlearning apps?",
	"Look up some stuff on microlearning?",
	"Start making a website?",
]